#ifndef __PROPERTIES_H__
#define __PROPERTIES_H__

G_BEGIN_DECLS

#define DEFAULT_COLOR_SCHEME "default"

enum Defaults {
	DEFAULT_SIZE = 40,
	DEFAULT_INTERVAL = 1000,
	DEFAULT_PADDING = 4,
	DEFAULT_SPACING = 4,
	DEFAULT_BORDER_WIDTH = 1,
	DEFAULT_BACKGROUND_DIRECTION = LOAD_GRADIENT_RADIAL,
};

G_END_DECLS

#endif /* __PROPERTIES_H__ */
